# Generated by Django 4.1 on 2023-01-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posApp", "0004_salesitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="product_count",
            field=models.IntegerField(default=1),
        ),
    ]
