# Generated by Django 3.2.5 on 2023-01-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_products_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='measurement_units',
            field=models.CharField(default='units', max_length=55),
        ),
    ]
