# Generated by Django 3.2.5 on 2023-01-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_productreturns'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='minimum_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_count',
            field=models.IntegerField(default=10),
        ),
    ]
