# Generated by Django 3.2.5 on 2023-01-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_auto_20230118_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='productreturns',
            options={'verbose_name': 'Product Returns', 'verbose_name_plural': 'Product Returns'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='salesitems',
            options={'verbose_name': 'Sales Items', 'verbose_name_plural': 'Sales Items'},
        ),
        migrations.AlterField(
            model_name='products',
            name='minimum_stock',
            field=models.IntegerField(default=1, help_text='warning, low stock!!!'),
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notify', to='posApp.products')),
            ],
        ),
    ]
