# Generated by Django 3.2.5 on 2023-01-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_notify_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruseCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_id', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name': 'Low Stock Notifications', 'verbose_name_plural': 'Low Stock Notifications'},
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='posApp.trusecustomerprofile'),
        ),
    ]
