# Generated by Django 3.2.5 on 2023-01-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_trusecustomerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusecustomerprofile',
            name='customer_id',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
