# Generated by Django 3.2.5 on 2023-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_rename_trusecustomerprofile_trustedcustomerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedcustomerprofile',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='trustedcustomerprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Customer Id'),
        ),
    ]
