# Generated by Django 3.2.5 on 2023-01-24 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0017_auto_20230124_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustedcustomerprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
