# Generated by Django 3.2.5 on 2023-01-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0018_alter_trustedcustomerprofile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustedcustomerprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
