# Generated by Django 3.2.5 on 2023-01-24 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0019_alter_trustedcustomerprofile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 19, 48, 48, 936632)),
        ),
    ]
