# Generated by Django 3.2.5 on 2023-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0021_alter_salesitems_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='buying_price',
            field=models.FloatField(default=0),
        ),
    ]
