# Generated by Django 3.2.5 on 2023-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0022_products_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bought_count',
            field=models.IntegerField(default=0),
        ),
    ]
