# Generated by Django 3.2.5 on 2023-01-29 10:35

from django.db import migrations, models
import posApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_products_bought_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to=posApp.models.product_image_path),
        ),
    ]
